Publish.css Integration into EbullientWorks
ebullient/obsidian-theme-ebullientworks pull request #26
Opened 2023-04-16 19:27 UTC by sigrunixia

This update brings Publish.css Integration into Ebullientworks. 
It include the update released yesterday to checkboxes.

It also removes .theme-dark .print as this is no longer needed in the next release of Obsidian, so this may be better tagged as a next version release. 

Thread is #25 .

2023-04-16 20:42 UTC, ebullient requested changes
More in a bit..

2023-04-16 20:42 UTC, ebullient commented on src/fragments/01a-colors-mixins.scss
Holy macaroni!! =)

I have one ask (which may be odd).. can you keep the base color groupings together at the top? Rainbow + grayscale. When I fuss with colors (which I don't do terribly often), I like the spectrum together.

I would be especially happy if they were in the same order as the original: 
red, yellow, green, cyan, blue, purple, pink .. then the gray, with all of the other mixins following.

2023-04-16 20:42 UTC, ebullient commented on images/publish-showcase/sample-calloits-light.png
maybe a filename typo. ;)

2023-04-16 20:42 UTC, ebullient commented on images/publish-showcase/sample-calloits-dark.png
maybe a filename typo. ;)

2023-04-16 20:42 UTC, ebullient commented on src/fragments/03-core-theme-light.scss
> -.theme-dark .print,
Before removing this, can you verify what happens when you print when you're in dark mode? Last I checked, the results were a little off.. So I basically flipped dark-mode to light mode if print was involved..

2023-04-16 20:42 UTC, ebullient commented on src/fragments/04-headings-hr-tags.scss
> +  .is-live-preview .HyperMD-header .cm-header::before,
🤦‍♀️

2023-04-16 20:42 UTC, ebullient commented on src/fragments/04-headings-hr-tags.scss
> +    content: '\00a7\00a0';
🤦‍♀️

2023-04-16 20:42 UTC, ebullient commented on src/fragments/04-headings-hr-tags.scss
> +  &.theme-dark,
There was a distinction here, as the settings applied only to the dark theme when printing: `&.theme-dark .print`

2023-04-16 20:42 UTC, ebullient commented on src/fragments/12-calendar-day-planner-tracker.scss
> +.theme-dark,
Again.. this originally applied only to dark-mode when printing...

2023-04-16 20:42 UTC, ebullient commented on src/fragments/13-timelines.scss
> +.theme-dark,
only dark mode when printing..

2023-04-16 21:17 UTC, sigrunixia commented on images/publish-showcase/sample-calloits-dark.png
Corrected

2023-04-16 21:17 UTC, sigrunixia commented on images/publish-showcase/sample-calloits-light.png
Corrected :)

2023-04-16 22:30 UTC, sigrunixia reviewed
Should be good to go. But I could always miss something. :)

2023-04-16 23:41 UTC, ebullient commented on src/fragments/15-table.scss
> -  --table-header-weight: var(--font-semibold);
```
  --table-header-border-color: var(--primary-accent-3);
  --table-header-weight: var(--font-semibold);
```

These were dropped?

2023-04-16 23:41 UTC, ebullient commented on src/publish.css.map
Did you mean to include this?

2023-04-16 23:41 UTC, ebullient commented on theme.css
Don't include this in the commit. Will come from the release..

2023-04-16 23:46 UTC, sigrunixia commented on src/fragments/15-table.scss
> -  --table-header-weight: var(--font-semibold);
What in the world. Yup. Fixing now.

2023-04-16 23:47 UTC, sigrunixia commented on src/publish.css.map
Never know if I should include those. Adding those to the "do not send, junk files" list.

2023-04-17 00:00 UTC, sigrunixia commented on theme.css
Deleted :)

2023-04-20 02:41 UTC, closed without merging